%%
% Exports a csv file of a generated trajectory for a two point line
% trajectory.
% Trajectory specifications

function ExportTrajectory( x_initial, ...
                        x_final, ...
                        x_velocity_initial, ...
                        x_velocity_final, ...
                        x_acceleration_initial, ...
                        x_acceleration_final, ...
                        y_initial, ...
                        y_final, ...
                        y_velocity_initial, ...
                        y_velocity_final, ...
                        y_acceleration_initial, ...
                        y_acceleration_final, ...
                        l1, ... //length of link 1
                        l2, ... //length of link 2
                        t_0, ...
                        t_final, ...
                        delta_t, ...
                        filename)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
time = t_0 : delta_t : t_final;

%%
% Generate the polynomial coefficients of the trajectory
x_coefficients = GenerateTaskTrajectoryCoeff(   t_0, ...
                                                t_final, ...
                                                x_initial, ...
                                                x_velocity_initial, ...
                                                x_acceleration_initial, ...
                                                x_final, ...
                                                x_velocity_final, ...
                                                x_acceleration_final);

y_coefficients = GenerateTaskTrajectoryCoeff(   t_0, ...
                                                t_final, ...
                                                y_initial, ...
                                                y_velocity_initial, ...
                                                y_acceleration_initial, ...
                                                y_final, ...
                                                y_velocity_final, ...
                                                y_acceleration_final);

%%
% Generate Task Space Trajectories

x_trajectory = GenerateTaskTrajectory(time, delta_t, x_coefficients);
y_trajectory = GenerateTaskTrajectory(time, delta_t, y_coefficients);

%%
% Generate Joint Space Trajectory

[   q1_trajectory, q1_velocity, q1_acceleration, ...
    q2_trajectory, q2_velocity, q2_acceleration] = ...
    GenerateJointTrajectory(x_trajectory, y_trajectory, delta_t, l1, l2);

Q_traj = [transpose(q1_trajectory), ...
          transpose(q1_velocity), ...
          transpose(q1_acceleration), ...
          transpose(q2_trajectory), ...
          transpose(q2_velocity), ...
          transpose(q2_acceleration)];
dlmwrite(filename, Q_traj, 'precision', '%.4f')
end
